services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    env_file:
      - ./server/.env

  client:
    build:
      context: ./Social-media
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
volumes:
  db-data:
