services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nest-network

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    networks:
      - nest-network

  client:
    build:
      context: ./Social-media
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - nest-network
volumes:
  db-data:

networks:
  nest-network:
